name: Candilib-Auto

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "7 10 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm ci
    - run: node .
      env: 
        TOKEN: ${{ secrets.TOKEN }}
        CREDENTIALS: ${{ secrets.CREDENTIALS }}
