name: Candilib-Auto

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "57 9 * * *" # 9:57 AM UTC is 11:57 AM in Paris

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm ci
    - run: node .
      env: 
        TOKEN: ${{ secrets.TOKEN }}
        CREDENTIALS: ${{ secrets.CREDENTIALS }}
